### ISSUE TITLE
Hide blocks that aren't relevant to client's website

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Blocks#12]
Add a "filter" that hides/disables blocks that clients won't ever use, which may come back to bite us later.

OR

If we spin up this plugin for each client, we could just delete our custom gutenblocks?

**Comment by jomurgel** [comment]
Would love to build in an options page to toggle block availability.

**Comment by coreymcollins** [comment]
@jomurgel do you mean block availability for our own custom blocks or for all registered Gutenberg blocks?
