### ISSUE TITLE
CPTUI-Extended Integration

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-blocks#31]
CPTUI-Extended is one of our premium plugins, and relies on a button added to TinyMCE for users to be able to access the modal, which then creates a shortcode (just like Gravity Forms). 

We need to come up with a way to access the modal once TinyMCE gives way to the Gutenberg/Blocks editor.

![screenshot](https://dl.dropbox.com/s/9ktmmyrpium0e2g/Screenshot%202018-03-20%2013.55.45.png?dl=0)

![screenshot](https://dl.dropbox.com/s/n0wlw0yko0r3juo/Screenshot%202018-03-20%2013.56.01.png?dl=0)

**Comment by coreymcollins** [comment]
Looks like this already works thanks to some backwards compatibility baked into Gutenberg:
![](https://dl.dropbox.com/s/8zwmtzrlnotnib1/cptui-it-works%21%21%21.gif?dl=0)

![](https://dl.dropbox.com/s/8vk8909j7idjq8f/Screenshot%202018-03-23%2014.00.01.jpg?dl=0)
