### ISSUE TITLE
Update GitHub Gist block so that the URL can be updated

### ISSUE THREAD

**Issue by kellenmace** [WebDevStudios/WDS-Blocks#36]
Currently, a URL can be entered only once and there isn't a way to change it. We should provide a field for updating it.

**Comment by kellenmace** [comment]
I have updated this block with controls for updating the gist URL after it's been initially set. I could use a little help styling the block controls, though - at some browser widths it is either too wide, or its bottom border collides with the border of the block below it. Example:
https://cloudup.com/caK0DzGUzOj

When the viewport is big enough, I'd like to make the block controls URL input field at least 350px wide, so you can t least see the beginning of the gist number in the URL.

@jomurgel – is this something you'd be willing to take a look at?

Thanks.

**Comment by ImBigWill** [comment]
I did some work in this branch for this block late last week/early this week. I'll need to double check some of it, as I did some other work for back end styling of blocks that might be redundant here, so I'll just need to double check that first thing tomorrow.

**Comment by jomurgel** [comment]
Made a couple of changes here and confirmed everything working on this, so I think we can issue a PR for the block updates, though I'm not 100% sure if this is all that was needed — styled form element and the ability to update which @ImBigWill and @kellenmace tackled already.

![kapture 2018-05-30 at 18 44 49](https://user-images.githubusercontent.com/5230729/40755029-b5c32a34-6439-11e8-9e10-248498e4fcce.gif)
