### ISSUE TITLE
Blogging Ideas

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Blocks#4]
Please take notes and blog about your experiences on webdevstudios.com

**Possible Topics:**

- How to install and use the WDS Gutenberg plugin
- How to develop with the WDS Gutenberg plugin
- How to contribute to the WDS Gutenberg plugin

Assign to Greg for review.

** remember, this won't be called Gutenberg at some point.

**Comment by jomurgel** [comment]
Topic: Gutenberg Multi-select Component. 

- Need to pull out the component into its own component from "New Related Posts".

**Comment by gregrickaby** [comment]
We should write a high-level "shipping phase 1" blog post!
