### ISSUE TITLE
"WDS Blocks requires that the WordPress Gutenberg plugin is activated." error notice displays on all pages, with Gutenberg active.

### ISSUE THREAD

**Issue by davidlaietta** [WebDevStudios/WDS-Blocks#45]
I am running WP v4.9.5 on a staging site with Gutenberg v2.7.0

When I activate WDS Blocks after already having Gutenberg active on the site, the error notice "WDS Blocks requires that the WordPress Gutenberg plugin is activated." is displayed on every admin page. If I deactivate and reactive both plugins, one after another, the error notice persists.
![screenshot 2018-04-28 12 51 01](https://user-images.githubusercontent.com/1971070/39398963-9fa61fdc-4ae3-11e8-82bb-f5919030c0aa.png)

**Comment by gregrickaby** [comment]
Thanks for the report @davidlaietta. At first glance I'm not able to replicate this. Are you using the Gutenberg plugin from .org? Or the Github version?

**Comment by gregrickaby** [comment]
I spoke to soon. When I download a .zip of our repo vs cloning, I get the same error.

**Comment by gregrickaby** [comment]
@davidlaietta Figured it out. You need to rename this plugin's folder from `WDS-Blocks-1.0` to `wds-blocks`.

I'll add this to the README. Thanks again for reporting it! 👍

**Comment by gregrickaby** [comment]
Fixed with https://github.com/WebDevStudios/WDS-Blocks/commit/45fd30f7e1edd592b39e63f02cb9e98f396e2ec0

Issued a quick hotfix release: https://github.com/WebDevStudios/WDS-Blocks/releases/tag/v1.0.1
