### ISSUE TITLE
Unable to remove/change background image on hero block

### ISSUE THREAD

**Issue by stirrell** [WebDevStudios/WDS-Blocks#49]
### Actual behavior ###
When having a background image set for a hero, it should be possible to remove or change the selected background image.

### Actual behavior ###
No way to remove a chosen image is shown.

### Steps to reproduce error ###

- Add a new Hero Block (WDS).
- Choose Background Type of Image.
- Select an image.

### Screenshots of error ###
![image](https://user-images.githubusercontent.com/2236935/39903476-66e741a4-54a1-11e8-8c02-2546e95e9229.png)

### Please include any relevant parts of your configuration ###
- Chrome 66
- WDS Blocks 1.0.3 and Gutenberg 2.8.0

Looking at the code, it looks like `src/components/background-options/index.js` is falling to `null` on the check for `props.focus ?` on line 86.

**Comment by jomurgel** [comment]
This issue appears to have been resolved with #52.

Affected both images and video uploads in background options.

![screenshot 2018-05-30 18 28 09](https://user-images.githubusercontent.com/5230729/40754672-a18b12f4-6437-11e8-836e-e0d38b517b9f.jpg)
![screenshot 2018-05-30 18 29 59](https://user-images.githubusercontent.com/5230729/40754674-a2e1717a-6437-11e8-83d9-db14aa2817e0.jpg)
