### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Blocks#5]
I'd love to utilize both the README and the Wiki: https://github.com/WebDevStudios/WDS-Gutenberg/wiki

**Goals**

- New developer onboarding
- New user "how to" documentation

**Comment by coreymcollins** [comment]
Current documentation in the wiki:

Block Versioning (using `deprecated`): https://github.com/WebDevStudios/wds-gutenberg/wiki/Block-Versioning

Blocks (adding/editing blocks): https://github.com/WebDevStudios/wds-gutenberg/wiki/Blocks

Creating A Block: https://github.com/WebDevStudios/wds-gutenberg/wiki/Creating-A-Block

Global Components: https://github.com/WebDevStudios/wds-gutenberg/wiki/Global-Components

**Comment by coreymcollins** [comment]
Added a custom sidebar to the wiki as well so we can have better page organization:
![](https://dl.dropbox.com/s/3r8ryudv4vz1b2e/Screenshot%202018-04-24%2013.48.22.jpg?dl=0)

This is 100% manual, so as we need to add new pages we need to edit the sidebar - but it's much better than Github's default listing of all pages alphabetically.

Clicking the pencil icon in the sidebar brings you to an edit page where we can freely edit things to our liking: https://github.com/WebDevStudios/wds-gutenberg/wiki/_Sidebar/_edit
![](https://dl.dropbox.com/s/xh0nykjlmftkt5c/Screenshot%202018-04-24%2013.49.26.jpg?dl=0)

**Comment by coreymcollins** [comment]
Right now the docs we have serve to:
- Provide Dev Onboarding (largely handled by the Readme, linked in the Wiki)
- List default Blocks and how to use them
- Detail how to create a Block
- Detail Block Versioning
- List our Components and how they are implemented/used

We will need to add additional details once the following Blocks are complete:
- [ ] Related Posts
- [ ] Recent Posts

We will need to add additional details for the following Components:
- [ ] Button Link (Built by @gregrickaby -- could you add the details for this?)
- [ ] MultiSelect (in progress by @efuller)

**Comment by coreymcollins** [comment]
Added Button Link documentation: https://github.com/WebDevStudios/wds-gutenberg/wiki/Global-Components#button-link

**Comment by coreymcollins** [comment]
Related & Recent Posts have been added by Jo & Eric.  I'm going to assign this to @efuller to handle adding `MultiSelect` as it seems a bit more involved, and writing its usage instructions may be better served by him.
