### ISSUE TITLE
Label for Background Type breaks into two lines in Background Options panel

### ISSUE THREAD

**Issue by stirrell** [WebDevStudios/WDS-Blocks#50]
The label for the Background Type dropdown looks a little strange because it breaks after the first word. The reason for this is that a label can only take up 75% of the width of the panel row and, in this case, it only goes as wide as the select. I think in this case, it would probably be safe to bump the max width up for this label:

```
.wds-background-options {
	.components-panel__row label {
		max-width: 95%;
	}
}
```

### Expected behavior ###
The label should not break after the first word but instead display on a single line.

### Actual behavior ###
The label is broken into two lines.

### Steps to reproduce error ###
On the Hero Block, go to the Background Options panel.

### Screenshots of error ###
![image](https://user-images.githubusercontent.com/2236935/39904093-47b7e114-54a4-11e8-9b8a-7edcd1f66f41.png)

### Please include any relevant parts of your configuration ###
- Chrome 66
- WDS-Blocks 1.0.3 and Gutenberg 2.8.0.

**Comment by jomurgel** [comment]
This issue appears to have been resolved with #52.

![screenshot 2018-05-30 18 26 14](https://user-images.githubusercontent.com/5230729/40754659-99f21c90-6437-11e8-9e31-d47649dfc799.jpg)
