### ISSUE TITLE
Title/Subtitle no longer accept text

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Blocks#51]
### Expected behaivor ###
When clicking into the title or subtitle fields, I should be able to add text.

### Actual behaivor ###
Unable to even click into these fields

### Steps to repoduce error ###
Upgrade the WordPress Gutenberg plugin from v2.7 -> 2.9

**Comment by jomurgel** [comment]
This issue appears to have been resolved with #52.
