### ISSUE TITLE
Gutenberg v3.2 Compatibility 

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Blocks#53]
I've completed some basic testing of all the WDS Blocks against Gutenberg v3.2.

https://demo.wdslab.com | Chrome 67

**Works ✅**

- Hero
- Call To Action
- Github Gist
- Recent Posts
- Two Column

**Broken 💔**

- Related Posts
- Users Grid

**Another Major Issue 🤕**

When you create a page/post using WDS Blocks. Everything seems to work (sans the broken blocks). BUT when you close the page/post in the dashboard, and then return to it later? The page appears to have reset to "Hello world"! 

![screenshot](https://dl.dropbox.com/s/atkj553v6sb7anf/Screenshot%202018-07-17%2009.03.26.png?dl=0)

If you preview the post in code editor tab:

![screenshot](https://dl.dropbox.com/s/ea6oj5aqdnvj32u/Screenshot%202018-07-17%2009.06.16.png?dl=0)

But if you open this page in Classic Editor? Everything is there...

![screenshot](https://dl.dropbox.com/s/nh42h4bcgcmpqex/Screenshot%202018-07-17%2009.07.01.png?dl=0)

**Comment by jomurgel** [comment]
There may be some conflicts with ACF Pro v. 5.6.10 which, upon update to 5.7 resolves several issues including ACF overriding the `wp.hooks` call. https://github.com/AdvancedCustomFields/acf/issues/31

Continuing the dive.

**Comment by jomurgel** [comment]
Looks like the update for ACF fixed the Users Grid problem. Unclear why, however, the Related Posts wasn't also broken, but none the less.

Looks like the problem child Re: the defaulting to the Classic Editor view only happens (for me) if the Recent Posts block is present.

Continuing the dive.
