### ISSUE TITLE
Run Block Audits

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/WDS-Blocks#59]
I'd like to run an audit on all of the WDS Blocks blocks to confirm everything is working as expected. A cursory check before the release of 1.0.5, support for 3.4.0, checked out, but I didn't check all of the use cases.

[Reference](https://wordpress.org/gutenberg/handbook/)
[Document for tracking](https://docs.google.com/document/d/1HelYWkYQPRegKgtO-oT1pStDHyY4b-NCgINdXUK-lJ8/edit#heading=h.e4ql33loxw2s)

## Perform Audit
1. Audit. Perform an audit code and see where we could maybe improve or refactor to be more performant. 
2. Extend and cleanup. There may be some additional functions/hooks that we could leverage to improve some of our blocks, [Extending Blocks](https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/) for example wasn't around when this project started.
3. Potential Style cleanup. Figuring out if and where we can clean up up the styles. [Extending the Editor UI](https://wordpress.org/gutenberg/handbook/extensibility/#extending-the-editor-ui) might be a good place to start. Keep things consistent with the Gutenberg UI or with the WDS styles.
4. Organize. Update/organize the Gutenberg "Add Block" pop-down. Some are in Common Blocks, others in Widgets, others in Formatting. Just want to make sure they're being housed in the correct places.

## Blocks to Audit
- [ ] Call to Action
- [ ] Default
- [ ] Hero
- [ ] Two Column
- [ ] Related Posts
- [ ] Github Gist
- [ ] Recent Posts

## Components to Audit
- [ ] Background Options
- [ ] Text Options
- [ ] Other Options

## Related
#60 

## Next Steps
Once an audit is complete we'll create issues for said blocks to outline potential improvements for a 1.1 release.

**Comment by coreymcollins** [comment]
I started looking at some of the Extending Blocks functionality today - I had a thought/hope that we could potentially move some of the code we have in place to set background elements (images, colors, etc.) out of the blocks and just display them via the hook.  It doesn't look like this works, at least on a first pass, as the `blocks.getSaveContent.extraProps` looks to either apply a static background (in this example) but fails if you try to pull the value saved for each individual block.

I want to dig in deeper to see if that is something we can tap into because it'd be much nicer to not have to have devs worry about manually including those lines of code to get our background elements in place. 🤔

**Comment by coreymcollins** [comment]
Update: I may be a liar who just figured out a (somewhat janky) way of doing this.  Still poking around and learning about Extending Blocks.

**Comment by jomurgel** [comment]
I've like to get this plugin in line with the new WDS plugin framework structure so that we can get things a bit more organized than it is now.

**Comment by jomurgel** [comment]
Looking at the blocks as they currently exist I wonder about a few things, up for discussions.

## Notes
First, the **CTA** and **Hero Blocks** are very similar, both, to the cover, or heading blocks. Essentially the appearance of either could be emulated with out-of-the-box Gutenberg blocks. I think it's important to determine what, specifically, our WDS Blocks brings that's different than the default blocks. Those things could be:
- The background image, video, color options are not typically available outside of WDS Blocks.
- Text color is not available in these default blocks.
- Additional button feature.

Each of these is generally much more robust than default blocks, but that begs the question. Could we just add the background, font color, or button features to existing blocks by extending the default blocks?

https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/

The **two column block** also already exists, so we should think about how our block differs. Other than the block options above, the Media & Text block functions identically. I think it might make sense to either remove this block and attempt to extend the options.

We should probably remove the **default block** if it's only going to be used as a starting point.

**Recent Posts** is 80% the same as the default Latest Posts block in WP. Our block extends the category/tag functionality, so this is, in my opinion, a vast improvement over the current block, but I think extending the functionality of Latest Posts is probably going to be more efficient and easier to debug than maintaining the current block. The other option would be to rebuild this block entirely.

**Related Posts** is the most unique block of WDS Blocks leveraging the search feature/function and two-pain view with off-focus render. I think this should just be cleaned up.

**Gist Block** should be kept and improved as the default "embed" block no longer allows embedding of Gists out of the box, and this would be helpful.

## Optional
I'd like to add an options page to disable/enable blocks globally or by post type. I can concievably see 

## Takeaway
Overall I think we need to refactor and resolve issues with blocks. The issues seem to stem from addition of several new width/alignment features.

We need to set the theme/plugin color defaults with PHP, and/or at the least have these tested and set within a branch of WD_s, noted in https://github.com/WebDevStudios/wd_s/issues/456 and get a set of styles together so that all of the WDS blocks are in line with one another.

## Important
The biggest issue with WDS Blocks right now is that it activates, but is not available on the latest version of WordPress (5.0.3 at the time of this comment). So that should be the first thing to look into.
