### ISSUE TITLE
Replace withAPIData

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/WDS-Blocks#63]
Getting this message in the console with the latest update:
```wp.components.withAPIData is deprecated and will be removed from Gutenberg in 3.7. Please use the Core Data Module or wp.apiFetch directly instead.```

We'll need to update our **Recent Posts** block and **Post Render** component part for this change.

### Please include any relevant parts of your configuration ###
- Gutenberg 3.5
- https://wordpress.org/gutenberg/handbook/reference/deprecated/#3-7-0

**Comment by jomurgel** [comment]
We can reference the core `Latest Posts` block which utilizes `withSelect` to replace `withAPIData` which is very similar in the way our `Recent Posts` block works.

https://github.com/WordPress/gutenberg/blob/ad889ba844a30133ac200896df1bd991d5fb0bde/packages/block-library/src/latest-posts/edit.js#L154

From what I can tell wth apiFetch is used to return an api response back directly ala `apiFetch( URLHERE )` where as `withSelect` allows us to dive down a little there with internal data from what I can tell.

https://github.com/WordPress/gutenberg/tree/master/packages/data and https://wordpress.org/gutenberg/handbook/packages/packages-data/#withselect-mapselecttoprops-function-function
