### ISSUE TITLE
Uncaught TypeError: Cannot read property 'PlainText' of undefined

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/WDS-Blocks#75]
### Expected behavior ###
Should be able to use our blocks without issues or errors.

### Actual behavior ###
Error displayed in console when trying to pull components from `wp.editor`:
![](https://dl.dropbox.com/s/wkkou0vg4hybui4/Screenshot%202018-10-25%2010.19.52.jpg?dl=0)

This is not an issue in WP 4.9.8 and Gutenberg 4.1.0, but in future-testing 5.0 I'm running into this problem.

The error above is pointing to our Block Title component:
![](https://dl.dropbox.com/s/gz4j8101u0cbbra/Screenshot%202018-10-25%2010.26.30.jpg?dl=0)

I tested removing the line calling PlainText and setting the render for Block Title to `null` and I get a console error for the next time something is called from `wp.editor` in Background Options:
![](https://dl.dropbox.com/s/098r966o5354t8f/Screenshot%202018-10-25%2010.28.29.jpg?dl=0)

### Steps to reproduce error ###
Active everything as noted in the config section below and view the console when adding a page.

### Screenshots of error ###
![](https://dl.dropbox.com/s/wkkou0vg4hybui4/Screenshot%202018-10-25%2010.19.52.jpg?dl=0)

### Please include any relevant parts of your configuration ###
WP 5.0-beta1-43823
ACF Pro 5.7.7
WDS Blocks 1.0.7 (fresh pull from master)

**Comment by jomurgel** [comment]
Looks like there might be a bunch of JS errors in 5.0 Beta 1. https://make.wordpress.org/core/2018/10/24/wordpress-5-0-beta-1-update/

**Comment by coreymcollins** [comment]
Closed via #76
