### ISSUE TITLE
WDS Blocks 2.0: wd_s

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-blocks#81]
WDS Blocks will be paired with wd_s. Please coordinate with @coreymcollins on testing and verification.

**Comment by asharirfan** [comment]
### WDS Blocks v2.0

The proposed list of WDS Blocks for v2.0. Please add your block suggestions to this list.

- [ ] [Accordion Block](https://github.com/WebDevStudios/WDS-Blocks/issues/78)
- [ ] [Carousel Block](https://github.com/WebDevStudios/WDS-Blocks/issues/79)
